### ISSUE TITLE
Ext-React not usable with the classic toolkit !

### ISSUE THREAD

**Issue by eucaos** [sencha/ext-react#85]
**Standard html elements (like <div />) are not rendered when using ext-react with the classic toolkit.**

Steps to reproduce:

1. Install ext-react classic toolkit boilerplate from here https://github.com/sencha/ext-react/tree/master/packages/ext-react-classic-boilerplate
2. In https://github.com/sencha/ext-react/blob/master/packages/ext-react-classic-boilerplate/src/index.js file change

		<ExtReact>
           <AppContainer>
	            <Component />
           </AppContainer>
         </ExtReact>

   To

		 <ExtReact>
           <AppContainer>
	            <div>asd</div>
           </AppContainer>
         </ExtReact>

3. Run the application with npm start
4. Exception is thrown

ExtRenderer.js:179 Uncaught TypeError: Cannot read property 'dom' of undefined
    at finalizeInitialChildren (ExtRenderer.js:179)
    at completeWork (react-reconciler.development.js:6146)
    at completeUnitOfWork (react-reconciler.development.js:7751)
    at performUnitOfWork (react-reconciler.development.js:7928)
    at workLoop (react-reconciler.development.js:7940)
    at renderRoot (react-reconciler.development.js:7980)
    at performWorkOnRoot (react-reconciler.development.js:8598)
    at performWork (react-reconciler.development.js:8520)
    at performSyncWork (react-reconciler.development.js:8492)
    at requestWork (react-reconciler.development.js:8392)

I traced the problem back to this to lines in Extrenderer.js

var cmp = Ext.create({ xtype: 'component', cls: 'x-react-element' });
ReactDOM.render(React.createElement(type, props, props.children), cmp.el.dom);

el is undefined on cmp, which is not the case if you use the modern toolkit.
The Ext.create function provides the el field when using the modern toolkit.

Alternatively you can also try directly this custom made example here https://github.com/eucaos/ext-react-6.6-bug

**Comment by nmatei** [comment]
same for me:
the example from https://github.com/sencha/ext-react#using-html-elements-and-non-ext-js-components-inside-of-ext-js-components
is not working (just tried to add a panel with some html components, instead of Panel from (https://github.com/sencha/ext-react/blob/master/packages/ext-react-classic-boilerplate/src/App.js))

**Comment by branflake2267** [comment]
Thanks for reporting. I'll check this out.

**Comment by eucaos** [comment]
@branflake2267 Any update on this ? We waited a long time to get this release, and now we can't integrate it to be able to move to React 16.

**Comment by branflake2267** [comment]
I'm checking with the team. Back soon.

**Comment by mgusmano** [comment]
We just released ExtReact 6.6.1 to this git repo - should be fixed there.  The 6.6.1 release should be in the sencha npm repo later today

**Comment by mgusmano** [comment]
6.6.1 is now in production npm

**Comment by nmatei** [comment]
don't know how but the classic boiler plate still does not show html content inside a panel...
now I don't get errors but I'm not able to see the content of the panel if is plain html.

`<Panel title={this.title}>
                <div>content <strong>Strong</strong></div>
            </Panel>`

**Comment by eucaos** [comment]
@branflake2267 @mgusmano 
I installed the 6.6.1 update but it only works for the simple case in the first example.
As soon as I wrap a html component inside an ExtJs component it stops working.
Ex:

```
<ExtReact>
      <AppContainer>
        <Panel>
          <div>test</div>
        </Panel>
      </AppContainer>
    </ExtReact>
```

**Comment by branflake2267** [comment]
Sorry for the delay, we're working our way to this.

**Comment by eucaos** [comment]
> Sorry for the delay, we're working our way to this.

@branflake2267 How is this progressing ? Any chance to have a fix this week ?

**Comment by mgusmano** [comment]
I have v6.6.2 in the repo now for testing - can you try your use-case and let me know if it is fixed?

**Comment by eucaos** [comment]
@mgusmano 
I tried to copy only the new 6.6.2 dependencies : (ext-react, ext-react-babel-plugin, ext-react-renderercell, ext-react-transition and ext-react-webpack-plugin) directly in the node_modules folder, as I can't install them with npm until they are published.

I can't make it work like this, what I get now is :

GET http://localhost:5000/ext-react/ext.css net::ERR_ABORTED 404 (Not Found)
GET http://localhost:5000/ext-react/ext.js net::ERR_ABORTED 404 (Not Found)

**Comment by nmatei** [comment]
not fixed for my case:
i've been able to replace all changed versions like this:
replace : 
c:\Products\ext-react\packages\ext-react-classic-boilerplate\node_modules\@sencha\
   ext-react, ext-react-renderercell, ext-react-transition, ext-react-webpack-plugin, ext-react-babel-plugin
with the once from:
c:\Products\ext-react\packages
the app runs, but the bug is not fixed:
I've added an fiddle example: https://fiddle.sencha.com/#view/editor&fiddle/2ls2

The fiddle app does not show version ext-react-6.6.1 and this example is not running at all.

**Comment by eucaos** [comment]
@mgusmano @branflake2267 
Hey guys, is this issue blocked in some way ? We are trying for a long time now to move to this version of Ext-React which supports React 16.x.

**Comment by eucaos** [comment]
@mgusmano @branflake2267
I saw that ext-react 6.6.2 package has appeared on Sencha npm. 
I eagerly downloaded the classic boilerplate again, but it still doesn't work for the simplest html test `<ExtReact>
      <AppContainer>
        <Panel>
          <div>test</div>
        </Panel>
      </AppContainer>
    </ExtReact>`

It't doesn't render any html that is wrapped in an Ext component.

I really hope you don't release the 6.6.2 version until this works. It's unusable for us in this form :(

**Comment by branflake2267** [comment]
Thanks for the report. I'll check with the team and get back.

**Comment by js-chris** [comment]
Is there any update on this? I would also test, if you have a new version (with 6.6.2 it is still not possible to render ExtReact components inside HTML components).

Thanks
Chris

**Comment by nmatei** [comment]
not working for me :(
i'll try on other pc to make sure is "clean"
I still get it an empty panel (even the new example)

**Comment by eucaos** [comment]
The new "ext-react-classic-demo" sample still doesn't work for us.

I uploaded a locally compiled verison of it here https://drive.google.com/file/d/1wWuY1-DZ1m-p45x-hKi8aAFI5YzcNoCy/view

You can try to download it and run it with npm start.

**Comment by nmatei** [comment]
yep,
on my personal laptop I get 6.6.3 in: ext-react-classic-boilerplate\node_modules\@sencha\ext-react\package.json
```
"name": "@sencha/ext-react",
"version": "6.6.3",
```
even in package dependencies I have
 "@sencha/ext-react": "~6.6.2"

don't know what happend

**Comment by eucaos** [comment]
It's clear then, this will not work until the ext-react 6.6.3 package is released.

**Comment by js-chris** [comment]
I was not able to use / update to 6.6.3, even with a clean install. 
Also "Use the github as the path to the 6.6.3 packages" was not working for me, maybe I missed something. Can you provide an example?

And does 6..6.3 also fix the issue "ExtReact Component inside Plain HTML"?
https://www.sencha.com/forum/showthread.php?470843-ExtReact-Component-inside-Plain-HTML

Thanks
Chris

**Comment by nmatei** [comment]
I made this: https://github.com/sencha/ext-react#to-use-this-repo-as-is-to-run-the-demos-on-your-local-machine

clone, npm install

open any example package (i've tested ext-react-classic-boilerplate, ext-react-classic-demo), and run: 
`npm start` (don't install anymore). 
inside node_modules the ext-react version is 6.6.3

**Comment by js-chris** [comment]
@nmatei thanks, I tried your proposal and I could install 6.6.3.

Unfortunately this did not solve my problem:
"ExtReact Component inside Plain HTML"?
https://www.sencha.com/forum/showthread.php?470843-ExtReact-Component-inside-Plain-HTML

@branflake2267, @mgusmano 
Can you provide a timing, when this will be fixed? I was waiting a long time to use React 16 and it is impossible to use ext-react 6.6.x with this issues.

**Comment by nmatei** [comment]
@js-chris you are right :) 
your flow still dows not work for me if I add a Button inside plain html.

**Comment by eucaos** [comment]
@branflake2267, @mgusmano
Seriously guys ?
Now we can't have EXT components inside normal HTML tags ?
I trying for a month an half now to use the latest version of ExtReact and I can't make it work :(

**Comment by branflake2267** [comment]
Thanks for reporting! I'll see what we can do to get that fixe.d

**Comment by eucaos** [comment]
@branflake2267, @mgusmano 

Ok, I will write down the minimal use cases needed for this to be usable:

1. HTML components inside EXTJS components
2. HTML components inside REACT components
3. EXTJS components inside HTML components
4. EXTJS components inside REACT components
5. REACT components inside HTML components
6. REACT components inside EXTJS components

**Comment by js-chris** [comment]
@branflake2267, @mgusmano 

Could you at least tell us what your plans are? I can't believe i paid for this software and i don't even get a decent feedback yet.

**Comment by eucaos** [comment]
@branflake2267, @mgusmano

It's almost a month now. Any progress fixing this?
We really want to use this.

**Comment by jasel-lewis** [comment]
> I now can confirm that on my personal laptop works. don't know why on other does not...
> had to add new Environment Variable:
> `_JAVA_OPTIONS=-Xmx1024m`

@nmatei Where did you add this environment variable?  I've tried everywhere I can think of without luck.  Have tried as a:
- Global Windows environment variable (both as `_JAVA_OPTIONS` and `JAVA_OPTIONS`)
- As a config to `webpack-dev-server` as `--env._JAVA_OPTIONS...` and `--env._JAVA_OPTIONS...`
- As a config to `npm` using both `cross-env` and as the `--max_old_space_size` config
- As a config to `node` using `--max_old_space_size`

I'm at a loss to get around the "Java heap space" error

**Comment by jasel-lewis** [comment]
@branflake2267 You helped me realize my _boneheaded_ move.  I keep forgetting that _global_ environment variables are not easily reloaded.  Without some fancy footwork (scripts), Powershell will not get the updated `env` variables unless you close Powershell and reopen (or whatever you choose to use as your shell).  I'm using Visual Studio Code, so not even opening a new Terminal worked - had to close and reopen VSC.

The link you sent jogged my memory, so thank you!  After a bunch of monkeying around, I've confirmed that @nmatei is correct, the environment variable needs to be named `_JAVA_OPTIONS` (not `_JAVA_OPTS` as the link states).  Setting it to `-Xmx1024m` worked just fine in allowing me to `npm start` my Ext boilerplate installation.  So thank you to both of you!

One helpful hint to others: setting a global variable makes my skin crawl (especially when working within a team environment).  I was able to set the heap space within the package.json `start` script of the boilerplate project and everything worked (yes, and I remembered to test with the global variable deleted _and_ VSC restarted :) ).

Simply use the ubiquitous `cross-env` thusly:
`"start": "cross-env _JAVA_OPTIONS=-Xmx1024m npm run dev"`

**Comment by branflake2267** [comment]
Nice job figuring that out. And thanks for sharing. 

I'll ask if we can get our default heap raised too, it comes up often.

**Comment by eucaos** [comment]
Still testing ?

**Comment by jnsencha** [comment]
@eucaos We are very close to releasing the newest version of ExtReact. In this version the boilerplate project does compile and run properly. We are currently debugging a single, remaining (known) issue, on Windows. Once resolved we will do another round of testing internally then push this out to production. Thanks for your patience.

**Comment by jnsencha** [comment]
We are very, very close! We’ve just completed that last major bug fix (windows related).

Jordan Nelson
Sencha Product Architect
Cell: (206) 637-3174
*: jordan.nelson@sencha.com | www.sencha.com

**Comment by dford07** [comment]
@jnsencha 
Is there an ETA on the next release?

**Comment by jnsencha** [comment]
@dford07 Sorry for the delay, we are rolling the next updating into Ext-React 6.7! It's in the final review stages. Our goal is end of Jan / Early February.

**Comment by jnsencha** [comment]
@dustinmcmanus2 I'll work with the team to test on Windows Server 2016 dev. My previous comment mentioned this fix briefly. There was a path resolve issue on Windows that has been fixed and lives in 6.7

**Comment by eucaos** [comment]
@jnsencha  And here we are, it's early February as you mentioned, is the Ext-React 6.7 release anywhere close ?

**Comment by jnsencha** [comment]
@eucaos It's very, very close! Thanks for your patience.

**Comment by nmatei** [comment]
until we wait for it to be closer to us :) can someone look approve https://github.com/sencha/extjs-reactor/pull/771 ? we are using ext-reactor until you release ext-react@6.7 and even then we don't know if it will work for all cases when we will migrate... so some small fixes on old product are also good. Thanks in advance!

**Comment by eucaos** [comment]
@jnsencha It's been two weeks now again, how many more we have to wait for the Ext-React 6.7 release ?

**Comment by jnsencha** [comment]
My apologies guys. 6.7 is still in the QE pipe. Trust me when I say I'll be very happy to get this released!

**Comment by jnsencha** [comment]
Not sure if you saw this, in progress now: Thursday, Feb. 28 @ 1pm ET: Sencha React Developer Tool Training – ExtReact. Link to register: https://register.gotowebinar.com/register/3321471092908116994

**Comment by eucaos** [comment]
@jnsencha  Does this mean you are closer to a release now ?

**Comment by eucaos** [comment]
@mgusmano @jnsencha 

I followed the Ext-React training link above.
Guys, you are showing things that are not available to us. 
Ext-React 6.7.0 is not available on Sencha npm.
You must stop doing this. Is confusing for everybody.

![image](https://user-images.githubusercontent.com/6533163/53720089-86c3a380-3e68-11e9-8317-fb2bbef22a50.png)

**Comment by jnsencha** [comment]
@eucaos I'm sorry for the confusion. I agree it is never ideal. I wanted make sure folks here got the chance to see the webinar, ask questions, etc. - even while knowing 6.7 wasn't going to be released at the time. 

That being said, 6.7.0 is now available on Sencha NPM (https://npm.sencha.com). PR Update will be coming soon.

**Comment by eucaos** [comment]
@jnsencha 
This is great news. We can't wait to test this. 
Do you know if this works with the react 16.8.0 ? as React 16.8.0 is the first release to support Hooks

**Comment by jnsencha** [comment]
@eucaos 16.8.3 is the latest we have verified compatibility with!

**Comment by eucaos** [comment]
@jnsencha 

I tested today the typescript boilerplate example from here https://github.com/sencha/ext-react/tree/ext-react-6.7.x/packages/ext-react-modern-typescript-boilerplate

Unfortunately it doesn't work :(
I'm aware you put a lot of effort  into this release, but we need a working sample that uses typescript.

Bellow is the error we get when running the typescript boilerplate

![image](https://user-images.githubusercontent.com/6533163/53866804-14cf9380-3ffb-11e9-8f7e-3da96b36772a.png)

**Comment by nmatei** [comment]
@eucaos same for me, i've created the js file from tsx for now:
ext-react\packages\ext-react-modern-typescript-boilerplate\src\index.tsx - index.js

**Comment by jnsencha** [comment]
Thanks @nmatei and @eucaos for reporting this

**Comment by eucaos** [comment]
@jnsencha 
Hello, we have trouble running the ExtReact 6.7 build in a lerna monorepo codebase.

More specifically, our "node_modules/@sencha" folder is lifted up from the packages folder to the root level by lerna,
the result being that the "node_modules/@sencha/ext" folder does not point to a valid location anymore.

In the past that was not an issue as it was configurable in the ExtReactPlugin options like this:

     `new ExtJSReactorWebpackPlugin({
          sdk: "../../node_modules/@sencha/ext",
          .....
          overrides: ["../../overrides", "overrides"],          
          packageDirs: [
            "../../node_modules/@sdl",
            "../../node_modules/@sencha",
            "../../ext-react/packages"
          ]          
        }),
`
With the new version we can't add the "sdk", "packageDirs" and "overrides" options anymore.

Can you please add those back or give us some advice how to workaround them ?

Thanks

**Comment by eucaos** [comment]
We are missing the typescript type definitions that were previously available on the extjs-reactor project.

I looked in your typescript-boilerplate example and they not appear there as well.
What happened to them ? Can we find them in some other place ?

From the typescript boilerplate example :

![image](https://user-images.githubusercontent.com/6533163/54133104-24e1db80-441e-11e9-9286-c69decde8b3c.png)


From old ext-reactor sample where it used to work:

![image](https://user-images.githubusercontent.com/6533163/54133476-d4b74900-441e-11e9-9f11-1b7e68f4667f.png)

**Comment by mgusmano** [comment]
I will look into the typescript definitions

**Comment by eucaos** [comment]
@mgusmano Any luck adding back the Typescript Type definitions ?

**Comment by eucaos** [comment]
> @jnsencha
> Hello, we have trouble running the ExtReact 6.7 build in a lerna monorepo codebase.
> 
> More specifically, our "node_modules/@sencha" folder is lifted up from the packages folder to the root level by lerna,
> the result being that the "node_modules/@sencha/ext" folder does not point to a valid location anymore.
> 
> In the past that was not an issue as it was configurable in the ExtReactPlugin options like this:
> 
> ```
>  `new ExtJSReactorWebpackPlugin({
>       sdk: "../../node_modules/@sencha/ext",
>       .....
>       overrides: ["../../overrides", "overrides"],          
>       packageDirs: [
>         "../../node_modules/@custom",
>         "../../node_modules/@sencha",
>         "../../ext-react/packages"
>       ]          
>     }),
> ```
> 
> `
> In the new ExtReact 6.7 version we can't add the "sdk", "packageDirs" and "overrides" options anymore.
> 
> Can you please add those back or give us some advice how to work around them ?
> 
> Thanks

Are there any updates/workarounds for this issue ? Thanks.

**Comment by mgusmano** [comment]
can we plan on doing a call to discuss these issues so I understand what you are seeing?

**Comment by eucaos** [comment]
I create a repo with the exact problem we have in context of using lerna and yarn workspaces here 
https://github.com/eucaos/ext-monorepo

Inside the repository we just copied an ext boilerplate example from here https://github.com/sencha/ext-react/tree/ext-react-6.7.x/packages/ext-react-modern-typescript-boilerplate

This is the error we get:
![image](https://user-images.githubusercontent.com/6533163/58808081-f5f49380-8621-11e9-8f1c-cad539ec6cfb.png)

This is a debug view
![image](https://user-images.githubusercontent.com/6533163/58808117-086ecd00-8622-11e9-94d4-2f1bd4966e79.png)

From what I see the expath, determined by process.cwd() is not good.

I tries to find node_modules in the package folder, but it's actually at the root of the ext-monorepo.

**Comment by eucaos** [comment]
@jnsencha Can you guys have a look a the issue described above. 
It would really make the difference for us to be able install and used the latest version of ext-react.

**Comment by thachp** [comment]
@jnsencha I'm having a similar problem with typescript boilerplate.

**Comment by eucaos** [comment]
@mgusmano @jnsencha

The ext-react lerna project would benefit as well if you configure lerna to "useWorkspaces": true.

Currently if I run lerna boostrap in the ext-react root, it takes a very long time to install and he space it occupies on the local drive is huge.

All this issues would be mitigated by using work-space's as it hoists common modules at the root level avoiding a lot of duplication and drastically reduce installation time.

**Comment by nmatei** [comment]
any news on typescript definition and lerna "useWorkspaces": true?

**Comment by jnsencha** [comment]
@eucaos @nmatei My apologies guys, circling back on this! @mgusmano will provide an update.

**Comment by nmatei** [comment]
> @eucaos @nmatei My apologies guys, circling back on this! @mgusmano will provide an update.

any updates?

**Comment by branflake2267** [comment]
The 7.1 should have the fixes.  We're nearly the last two weeks of development if all goes as planned, then the final phase of testing.

**Comment by branflake2267** [comment]
There's a possibility to try out the fixes in the early-adopter repo we have.

**Comment by nmatei** [comment]
Hi Brandon,
still can't use it as there are some missing packages in this repo, like:

"@sencha/ext-web-components": "~7.1.0",
"@sencha/ext-runtime-base": "~7.1.0",

and they are required inside @sencha/ext-react@7.1.0.

I can use some packages from local packages but not all... so can't install them all, yet..
"@sencha/ext-react": "file:../../@sencha/ext-react",
    "@sencha/ext-react-webpack-plugin": "file:../../@sencha/ext-react-webpack-plugin",
    "@sencha/ext-react-babel-plugin": "file:../../@sencha/ext-react-babel-plugin",

**Comment by branflake2267** [comment]
You'll want to get access to the early adopter repo, if you don't have access to those yet. Do you have access to the early adopter? If not email me and ask brandon.donnelson..sencha.com.
